### ISSUE TITLE
[IDEA]: getClusterByAddress(address)

### ISSUE THREAD

**Issue by zwergdev** [clustersxyz/sdk#5]
# Get the cluster from an address (one of connected)

### Idea
I tested the SDK on one of my projects, and I needed to display all the connected wallets of the cluster using a single active one. Overall, I accomplished this, but I would like to see a universal approach to obtaining the cluster by address.

### Function
```
const cluster = await clusters.getClusterByAddress('0xb87004a21b6bb529c17f874ee095f0c3344f0a9d');
```
### Returns
```
{
  "name": "zwerg/",
  "wallets": [
    {
      "type": "evm",
      "address": "0xb87004a21b6bb529c17f874ee095f0c3344f0a9d",
      "name": "zwerg/z",
      "isVerified": true
    },
    {
      "type": "solana",
      "address": "283aL8P2J2pnMmp77W8J4rX3ZHb2sAUwkNPA4ZMe4pcf",
      "name": "zwerg/sol",
      "isVerified": true
    }
  ]
}
```

**Comment by ryespresso** [comment]
Thanks for your suggestion. This endpoint should be coming out soon!

**Comment by ryespresso** [comment]
`getClusterByAddress` is now live in this sdk. Thanks for the idea!
